#!/bin/bash
background='#e37c44'
nextbg='#99ac4c'

read batterynr < .battery

if [[ $BLOCK_BUTTON = 1 ]]; then
  if [[ $batterynr = 0 ]]; then
    export batterynr=1
  else
    export batterynr=0
  fi
  echo $batterynr > .battery
fi


if [[ -z $batterynr ]];then
  export batterynr=0
  echo $batterynr > .battery
fi

battery=$(acpi -b | grep "Battery $batterynr")
regpercent="([0-9]{0,3})%"

if [[ $battery =~ $regpercent ]]
then
  percent=$(printf "%3d\n" ${BASH_REMATCH[1]})
  echo "<span background='$nextbg' foreground='$background'></span><span background='$background'> BAT$batterynr $percent% </span>"
else
  echo 'narp'
fi
